#ifndef PHYSICALALTERGLOBAL_H
#define PHYSICALALTERGLOBAL_H

#include "qglobal.h"

#if defined(PHYSICALALTER_LIBRARY)
#  define PHYSICALALTER_EXPORT Q_DECL_EXPORT
#else
#  define PHYSICALALTER_EXPORT Q_DECL_IMPORT
#endif

#endif // PHYSICALALTERGLOBAL_H
